# Generated by Django 2.2.17 on 2021-01-08 14:30

import django.contrib.auth.models
from django.db import migrations, models


def update_theme(apps, schema_editor):
    user_model = apps.get_model("users", "User")
    user_model.objects.all().update(theme="taiga")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210108_1430'),
    ]

    operations = [
        migrations.RunPython(update_theme)
    ]
